#############################################
#                                           #
#                   Houses                  #
#              Created by Jet315            #
#                                           #
#############################################
#Plugin depends on PlotSquared

#The prefix that is shown before the plugin
PluginsPrefix: "&6&lHOUSES &e&l> "

#The Locale being used (Must exist within the '/local' file)
Locale: "en-US"

#Whether to hide GUI items that the user does not have permission to use it
HideGUIItemsIfNoPermission: true

#What world are the houses located in?
PlotWorldName: 'houses'

#Put the ground level of the plot world, this prevents players breaking there houses (Players with 'house.admin.build' bypass this)
#If you want players to be able to break their houses, just put this as 255
MaxBuildHeight: 63
#Should users be able to place/break signs? (Used for chestshops on most servers)
AllowSignsInHouse: true

#Would you like confirmation messages to show (and for the player to type 'confirm' in chat) when upgrading/purchasing a house (These messages only show when clicking GUI options)
HouseConfirmation: true

#The plugin uses SQLite to store data - This is the name of the database
SQLiteTable: 'Houses'

#PURCHASING AND UPGRADING HOUSES
#Economy
#Use VAULT, TOKENS (https://www.spigotmc.org/resources/tokenmanager.8610/) or TOKENENCHANT (https://www.spigotmc.org/resources/tokenenchant.2287/)
EconomyTypeToUpgrade: TOKENS
#What should the cost of the first house be?
FirstHousePrice: 100
#Algorithm used to calculate the next house price
#Use {CURRENTHOUSELEVEL} to get the current house level
NextHousePrice: "(({CURRENTHOUSELEVEL}*3) * 500)*2"

#EXTENDING RENT TIME ON HOUSES
#Should houses expire after a certain time?
ShouldHousesExpire: true
#What type of economy would you like to use for extending time frames?
#Use VAULT, TOKENS (https://www.spigotmc.org/resources/tokenmanager.8610/) or TOKENENCHANT (https://www.spigotmc.org/resources/tokenenchant.2287/)
EconomyTypeToRent: VAULT
#The cost per day this will cost (Integers only)
CostToRentPerDay: 50000
#Max amount of time a player can rent a house for (In Days, integers only)
MaxAmountOfRentTime: 28
#The amount of rent time given to a user when he/she claims a house (In days, integers only)
GivenRentTime: 7
#Would you like to delete expired houses on startup? Will increase starting loading times depending on how big database is, however is suggested
DeleteExpiredHousesOnStartup: true

#Max House Level (This will prevent people from clicking 'upgrade' past this level)
MaxHouseLevel: 6
#How far above ground level (MaxBuildHeight) would you like to search for players chests when a house is upgraded? When using the default schematics - This number is fine. (This is so items can be transfered when a house is upgraded)
ChestSearchLevel: 30

#Commands to block - This blocks the basic /plot commands from running
#The message that is shown when a user runs this command is located in the locale file, under NonExistantPlotCommand
#The permission node needed to bypass this is house.admin.bypasscommands
CommandsToBlock:
  - "/p"
  - "/plot"
  - "/ps"
  - "/plotsquared"
  - "/p2"
  - "/2"
  - "/plotme"
  - "/plots"

#This delay is the time (in seconds) a player has to wait before being able to teleport (0 = instant teleport, with no message)
TimeToWaitWhenTeleporting: 0

#If this is enabled, when a plot is claimed the first schematic will be pasted onto the plot and have the above vectors applied to it.
#If you want the plot world to pre generate the first level houses, follow this tutorial: https://github.com/IntellectualSites/PlotSquared/wiki/Installation#initial-setup and disable this option
PasteFirstHouseOnClaim: true
#Schematic Paste Settings (when a house is claimed)
#I recommend that the plot sizes are the same sizes as the schematic
#By default, the schematics need to be moved down two. If you need to move them across or down at all, here is where you do that:
#VALUES MUST BE INTEGERS
MoveSchematicXDirection: 0
MoveSchematicYDirection: -2
MoveSchematicZDirection: 0


#Type in the name of the schematic you wish to place down when a house expires. Type "none" if you would like the default plot to show
#A valid schematic file located in the /houses/schematics folder needs to be present
#By default it will paste the first schematic in
SchematicOnExpirey: "house1.schematic"
MoveExpirySchematicXDirection: 0
MoveExpirySchematicYDirection: -2
MoveExpirySchematicZDirection: 0